Repository JEoN-Ha/Senior-Project, pull requests merged in 2020-12, with the labels that each got.

#31 readme update 해봤습니다!
  README.md
Labels: Pull Request, Review

#24 로그인, 로그아웃, 메뉴 구현 / 디자인 관련 문제점
  Armful/jeonha/.eslintcache
  Armful/jeonha/src/App.js
  Armful/jeonha/src/components/Component.css
  Armful/jeonha/src/components/Control.js
  Armful/jeonha/src/components/CustomerList.js
  Armful/jeonha/src/components/LoginContent.js
  Armful/jeonha/src/components/ReadCustomer.js
  Armful/jeonha/src/components/Subject.js
  Armful/jeonha/src/index.css
Labels: Pull Request

#41 수량 카운터, checked 구현 문제
  Armful/jeonha/.eslintcache
  Armful/jeonha/package-lock.json
  Armful/jeonha/package.json
  Armful/jeonha/src/components/Calculation.js
  Armful/jeonha/src/components/Menu.js
  Armful/jeonha/src/components/MenuInfo.js
  Armful/jeonha/src/store.js
  Armful/jeonha/yarn.lock
Labels: Pull Request, Question
