Repository JEoN-Ha/Senior-Project, pull requests merged in 2021-03, with the labels that each got.

#90 당위성을 위한 문서 작성
  main/README.md
Labels: Pull Request, Review

#87 Router code에 관하여
  fora22/DB/initDB.sql
  fora22/DB/initInsertDB.sql
  main/README.md
  main/drive_thru_web/server/dbconnection.js
  main/drive_thru_web/server/routes/router.js
  main/drive_thru_web/server/server.js
  main/drive_thru_web/src/App.js
  main/drive_thru_web/src/fetch/fetch.js
Labels: Bug, Discussion

#97 라우터 코드 수정
  main/drive_thru_web/server/routes/router.js
  main/drive_thru_web/src/component/Basket.js
Labels: Bug, Question
